platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/struts-example
    tag: latest
inputs:
- name: refapp-gateway-java
outputs:
- name: refapp-gateway-java-release
run:
  path: refapp-gateway-java/ci/tasks/refapp-gateway/compile/task.sh