platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/struts-example
    tag: latest
inputs:
- name: refapp-gateway-java
outputs:
- name: refapp-gateway-cast-artifacts
run:
  path: refapp-gateway-java/ci/tasks/refapp-gateway/bind-service/task.sh
params:
  CF_API: ((CF_API))
  CF_API_USER: ((CF_API_USER))
  CF_API_PASSWORD: ((CF_API_PASSWORD))
  CF_ORG: ((CF_ORG))
  CF_SPACE: ((CF_SPACE))
  REFAPP_SERVICE: ((REFAPP_SERVICE))